#!/bin/bash

set -ex

# PROOF_BASE_PATH="/var/tmp/agyso-daovote/proof/groth16"
PROOF_BASE_PATH="/var/tmp/agyso-daovote/proof/plonk"

submit_proof() {
    # rm -rf aligned_verification_data

    aligned submit \
    --proving_system GnarkPlonkBn254 \
    --proof "$PROOF_BASE_PATH/plonk.proof" \
    --public_input "$PROOF_BASE_PATH/plonk_pub_input.pub" \
    --vk "$PROOF_BASE_PATH/plonk.vk" \
    --batcher_url wss://batcher.alignedlayer.com \
    --network holesky \
    --rpc_url https://ethereum-holesky-rpc.publicnode.com 
}

submit_proof